title="Hamster Config"

[author]
name="Adnaan Badr"
organization="Hamster"
email="badr.adnaan@gmail.com"

[servers]

	[servers.local]
	port = 8686
	host = "http://localhost:8686"
	cookiesecret="mycookiesecret"

[databases]

	[databases.mongo]
	username =""
	password=""
	dbname=""
	host="mongodb://adnaan:pass@localhost:27017/hamster"
	port = 27017
	[databases.redis]
	port = 6379
	username =""
	password=""
	dbname=""
	host=""
	


[clients]
	
	[clients.browser]
	ip= "127.0.0.1"
	token="mysharedtoken"
	secret="YI1ZYdopn6usnQ/5gMAHg8+pNh6D0DdaJkytdoLWUj0="

[logins]
	
	[logins.google]
	id= ""
	secret=""
